// app/layout.tsx
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import Navbar from '@/app/(ui)/components/navbar/navbar.component'
import { MenuItems } from '@/app/(ui)/models/menu.model'

const menu: MenuItems[] = [
  { name: 'Home', url: '/' },
  { name: 'About', url: '/about' },
  { name: 'Services', url: '/services' },
  { name: 'Contact', url: '/contact' },
]

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'All Care Recruitment',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <div className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col h-screen`}>
        <Navbar menuItems={menu} />

        {/* Marquee */}
        <div className="bg-[#f5ada7] text-white h-12 flex items-center overflow-hidden">
          <p className="whitespace-nowrap animate-[scroll_15s_linear_infinite] px-2">
            Your world in our hands Your world in our hands Your world in our hands 
            Your world in our hands Your world in our hands 
          </p>
        </div>

        <main className="flex-1 flex flex-col bg-white">
          {children}
        </main>
      </div>

  )
}
