import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import Navbar from '@/app/(ui)/components/navbar/navbar.component'
import { MenuItems } from '@/app/(ui)/models/menu.model'

const menu: MenuItems[] = [
    {
        name: 'Home',
        url: '/'
    },
    {
        name: 'About',
        url: '/about'
    },
    {
        name: 'Services',
        url: '/services'
    },
    {
        name: 'Contact',
        url: '/contact'
    }
]

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'All Care Recruitment',
    description: 'Generated by create next app',
}

export default function PagesLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
            <Navbar menuItems={menu} />
            {children}
        </div>
    )
}
