name: Deploy to Production

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel Production Environment
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
